namePrefix: upcf-

resources:
- udrsim-deployment.yaml
- udrsim-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


configMapGenerator:
- name: udrsim-config
  files:
  - application.conf
  - logger.conf
  - certs/camel_git_cert.pem
  - certs/unrf_cert.pem
  - certs/unrf_key.pem