namePrefix: upcf-

resources:
- pesim-deployment.yaml
- pesim-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


configMapGenerator:
- name: pesim-config
  files:
  - application.conf