apiVersion: apps/v1
kind: Deployment
metadata:
  name: pesim
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pesim
  template:
    metadata:
      labels:
        app: pesim
    spec:
      containers:
      - image: camel.uangel.com:5000/upcf-pesim:latest
        name: pesim
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: UPCF_PESIM_CONFIG_FILE
          value: "/config/application.conf"
        - name: CONFIG_DIR
          value: "/config"
        volumeMounts:
        - name: pesim-config
          mountPath: /config
      volumes:
      - name: pesim-config
        configMap:
          name: pesim-config