apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

configMapGenerator:
  - name: upcf-config
    behavior: merge
    files:
    - jaegertrace.yaml 
    - logger.conf 
  - name: upcf-env
    behavior: merge
    envs:
    - desktop.env   