apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch
spec:
  schedule: "0 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: batch
    spec:
      template: 
        spec:
          containers:
          - image: camel.uangel.com:5000/uocf-batch:latest
            name: batch
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c 
            - batch
            env:
            - name: CONFIG_DIR
              value: "/config"  
            - name: UPCF_BATCH_CONFIG_FILE
              value: "/config/application.conf"
            - name: UPCF_DB_HOST_PORT
              value: "192.168.3.30"
            - name: UPCF_DB_USER
              value: "upcf"
            - name: UPCF_DB_PASSWORD
              value: "upcf.123!"
            - name: UPCF_REDIS_DB_HOST_PORT
              value: "192.168.3.30:6379"      
            volumeMounts:
            - name: batch-config
              mountPath: /config
          volumes:
          - name: batch-config
            configMap:
              # Provide the name of the ConfigMap containing the files you want
              # to add to the container
              name: batch-config