namePrefix: upcf-

resources:
- batch-deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


configMapGenerator:
- name: batch-config
  files:
  - application.conf
  - logger.conf