apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

command: ["/app/smfsim"]
args: ["-cps 100"]

bases:
- ../base

configMapGenerator:
  - name: smfsim-config
    behavior: merge
    files:
    - jaegertrace.yaml
    - application.conf
    - logger.conf        