apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - smfsim-meccom-deployment.yaml

bases:
- ../base

configMapGenerator:
  - name: smfsim-config
    behavior: merge
    files:
    - jaegertrace.yaml
    - application.conf
    - logger.conf        