namePrefix: upcf-

resources:
- batch-deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


configMapGenerator:
- name: batch-config
  files:
  - application.conf
  - logger.conf
- name: batch-env
  envs:
  - app.env

secretGenerator:
- name: mysql-creds
  literals:
  - username=upcf
  - password=upcf.123!
