apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: upcf-

resources:
- upcf-deployment.yaml
- upcf-svc.yaml

configMapGenerator:
- name: upcf-config
  files:
  - application.conf
  - logger.conf
  - jaegertrace.yaml  
  - certs/camel_git_cert.pem
  - certs/unrf_cert.pem
  - certs/unrf_key.pem
- name: upcf-env
  envs:
  - app.env