apiVersion: apps/v1
kind: Deployment
metadata:
  name: upcf
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: upcf
  template:
    metadata:
      labels:
        app: upcf
    spec:
      containers:
      - image: camel.uangel.com:5000/upcf:latest
        name: upcf
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 443
        envFrom:
        - configMapRef:
            name: upcf-env
        env:
          - name: UPCF_DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: username
          - name: UPCF_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: password
        volumeMounts:
        - name: upcf-config
          mountPath: /config
      volumes:
      - name: upcf-config
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: upcf-config