apiVersion: apps/v1
kind: Deployment
metadata:
  name: udrsim
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: udrsim
  template:
    metadata:
      labels:
        app: udrsim
    spec:
      containers:
      - image: camel.uangel.com:5000/upcf-udrsim:latest
        name: udrsim
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: UPCF_UDRSIM_CONFIG_FILE
          value: "/config/application.conf"
        - name: CONFIG_DIR
          value: "/config"
        volumeMounts:
        - name: udrsim-config
          mountPath: /config
      volumes:
      - name: udrsim-config
        configMap:
          name: udrsim-config