apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - upcf-meccom-deployment.yaml

bases:
- ../base

configMapGenerator:
  - name: upcf-config
    behavior: merge
    files:
    - jaegertrace.yaml 
    - logger.conf 
    - application.conf
  - name: upcf-env
    behavior: merge
    envs:
    - mec_com.env   